version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - menu
    environment:
      - POSTGRES_DB=menu
      - POSTGRES_USER=menu
      - POSTGRES_PASSWORD=menu123

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3344:3344
      - 5555:5555
    networks:
      - menu
    links:
      - db
    env_file:
      - .env.example
    platform: "linux/amd64"
    depends_on:
      - db

networks:
  menu:
    driver: bridge
