FROM --platform=linux/amd64 node:16

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

COPY ./dist /usr/src/app/dist

# Install app dependencies
RUN yarn install

# prisma global
RUN npm i -g prisma

EXPOSE 3344
EXPOSE 9229

CMD [ "yarn", "dev" ]
